### ISSUE TITLE
DLL Exceptions when loading a TTF font

### ISSUE THREAD

**Issue by DimucaTheDev** [opcon/QuickFont#57]
So, when using `new QFont(...)` I get "DLL freetype6 not found", or after some manipulations I get this:
`
System.BadImageFormatException: "Была сделана попытка загрузить программу, имеющую неверный формат. (0x8007000B)"
`
like "An attempt was made to load an incorrect format program"

code:
`
        _myFont = new QFont("Fonts\\ARIAL.TTF", 72, new QFontBuilderConfiguration(true));
        _drawing = new QFontDrawing();
`
full stack:
`
Unhandled exception. System.BadImageFormatException: Была сделана попытка загрузить программу, имеющую неверный формат. (0x8007000B)
   at SharpFont.FT.FT_Init_FreeType(IntPtr& alibrary)
   at SharpFont.Library..ctor()
   at QuickFont.FreeTypeFont..ctor(String fontPath, Single size, FontStyle style, Int32 superSampleLevels, Single scale)
   at QuickFont.QFont.GetFont(String fontPath, Single size, FontStyle style, Int32 superSampleLevels, Single scale)
   at QuickFont.QFont..ctor(String fontPath, Single size, QFontBuilderConfiguration config, FontStyle style)
   at SparkEngine.Program.OnLoad() in C:\Users\DimucaTheDev\source\repos\SparkEngine\Program.cs:line 316
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at SparkEngine.Program.Run() in C:\Users\DimucaTheDev\source\repos\SparkEngine\Program.cs:line 231
   at SparkEngine.Program.Main(String[] args_) in C:\Users\DimucaTheDev\source\repos\SparkEngine\Program.cs:line 192
`

Windows 11, NET 8
OpenTK, using Wayfinder.Quickfont nuget packet, latest version
Debug, X64
VC++ installed(2022)

tried to compile freetype6 myself, but i dunno how to get DLL instead of LIB

**Comment by DimucaTheDev** [comment]
p.s.: downloaded dll for windows from web caused the "Bad Image" issue, but now im stuck to where do i get normal freetype6.dll
